package kalkulator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-23T11:53:48.595+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "KalkulatorWrapped",
                  wsdlLocation = "file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC06-KalkulatorDocumentWrapper/WebContent/WEB-INF/wsdl/KalkulatorWrapped.wsdl",
                  targetNamespace = "http://www.example.org/KalkulatorWrapped/")
public class KalkulatorWrapped_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/KalkulatorWrapped/", "KalkulatorWrapped");
    public final static QName KalkulatorWrappedSOAP = new QName("http://www.example.org/KalkulatorWrapped/", "KalkulatorWrappedSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC06-KalkulatorDocumentWrapper/WebContent/WEB-INF/wsdl/KalkulatorWrapped.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KalkulatorWrapped_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC06-KalkulatorDocumentWrapper/WebContent/WEB-INF/wsdl/KalkulatorWrapped.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KalkulatorWrapped_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KalkulatorWrapped_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KalkulatorWrapped_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public KalkulatorWrapped_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KalkulatorWrapped_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KalkulatorWrapped_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns KalkulatorWrapped
     */
    @WebEndpoint(name = "KalkulatorWrappedSOAP")
    public KalkulatorWrapped getKalkulatorWrappedSOAP() {
        return super.getPort(KalkulatorWrappedSOAP, KalkulatorWrapped.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KalkulatorWrapped
     */
    @WebEndpoint(name = "KalkulatorWrappedSOAP")
    public KalkulatorWrapped getKalkulatorWrappedSOAP(WebServiceFeature... features) {
        return super.getPort(KalkulatorWrappedSOAP, KalkulatorWrapped.class, features);
    }

}
