package kalkulator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-23T11:53:48.558+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://www.example.org/KalkulatorWrapped/", name = "KalkulatorWrapped")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED) // to jest wartość domyślna, można by nie pisać
public interface KalkulatorWrapped {

    @WebMethod(action = "http://www.example.org/KalkulatorWrapped/sub")
    @RequestWrapper(localName = "sub", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.SubResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int sub(

        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/KalkulatorWrapped/add")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.AddResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int add(

        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/KalkulatorWrapped/div")
    @RequestWrapper(localName = "div", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.DivResponse")
    public void div(

        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(mode = WebParam.Mode.OUT, name = "quotient", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> quotient,
        @WebParam(mode = WebParam.Mode.OUT, name = "rest", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> rest
    );

    @WebMethod(action = "http://www.example.org/KalkulatorWrapped/inc")
    @RequestWrapper(localName = "inc", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.Inc")
    @ResponseWrapper(localName = "incResponse", targetNamespace = "http://www.example.org/KalkulatorWrapped/", className = "kalkulator.IncResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int inc(

        @WebParam(name = "arg", targetNamespace = "")
        int arg
    );
}
