
package kalkulator_bare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "kalkulator", targetNamespace = "http://www.example.org/kalkulator/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Kalkulator {


    /**
     * 
     * 				To jest operacja, która dodaje dwie liczby.
     * 			
     * 
     * @param parameters
     * @return
     *     returns kalkulator_bare.Wynik
     */
    @WebMethod(action = "http://www.example.org/kalkulator/add")
    @WebResult(name = "add-resp", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
    public Wynik add(
        @WebParam(name = "add-req", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
        DwieLiczby parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns kalkulator_bare.Wynik
     */
    @WebMethod(action = "http://www.example.org/kalkulator/sub")
    @WebResult(name = "sub-resp", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
    public Wynik sub(
        @WebParam(name = "sub-req", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
        DwieLiczby parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns kalkulator_bare.Wynik
     */
    @WebMethod(action = "http://www.example.org/kalkulator/mul")
    @WebResult(name = "mul-resp", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
    public Wynik mul(
        @WebParam(name = "mul-req", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
        DwieLiczby parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns kalkulator_bare.WynikDzielenia
     */
    @WebMethod(action = "http://www.example.org/kalkulator/div")
    @WebResult(name = "div-resp", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
    public WynikDzielenia div(
        @WebParam(name = "div-req", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
        DwieLiczby parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns kalkulator_bare.Wynik
     */
    @WebMethod(action = "http://www.example.org/kalkulator/sum")
    @WebResult(name = "sum-resp", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
    public Wynik sum(
        @WebParam(name = "sum-req", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
        WieleLiczb parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns kalkulator_bare.WynikDecimal
     */
    @WebMethod(action = "http://www.example.org/kalkulator/dzielenie")
    @WebResult(name = "dzielenie-resp", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
    public WynikDecimal dzielenie(
        @WebParam(name = "dzielenie-req", targetNamespace = "http://www.example.org/kalkulator/", partName = "parameters")
        OperacjaDzielenia parameters);

}
