
package ogloszenia.wygenerowane;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BladAplikacji", targetNamespace = "http://soap.ogloszenia/")
public class BladAplikacji_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BladAplikacji faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BladAplikacji_Exception(String message, BladAplikacji faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BladAplikacji_Exception(String message, BladAplikacji faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ogloszenia.wygenerowane.BladAplikacji
     */
    public BladAplikacji getFaultInfo() {
        return faultInfo;
    }

}
