
package ogloszenia.wygenerowane;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SerwisOgloszeniowy", targetNamespace = "http://soap.ogloszenia/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SerwisOgloszeniowy {


    /**
     * 
     * @param ogloszenie
     * @throws BladBazyDanych_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "zapiszOgloszenie", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.ZapiszOgloszenie")
    @ResponseWrapper(localName = "zapiszOgloszenieResponse", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.ZapiszOgloszenieResponse")
    public void zapiszOgloszenie(
        @WebParam(name = "ogloszenie", targetNamespace = "")
        OgloszenieSamochodowe ogloszenie)
        throws BladBazyDanych_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns byte[]
     * @throws BladAplikacji_Exception
     */
    @WebMethod
    @WebResult(name = "dane", targetNamespace = "")
    @RequestWrapper(localName = "foto", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.Foto")
    @ResponseWrapper(localName = "fotoResponse", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.FotoResponse")
    public byte[] foto(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws BladAplikacji_Exception
    ;

    /**
     * 
     * @param min
     * @param max
     * @return
     *     returns java.util.List<ogloszenia.wygenerowane.OgloszenieSamochodowe>
     * @throws BladBazyDanych_Exception
     */
    @WebMethod
    @WebResult(name = "ogloszenie", targetNamespace = "")
    @RequestWrapper(localName = "ogloszeniaWgCeny", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.OgloszeniaWgCeny")
    @ResponseWrapper(localName = "ogloszeniaWgCenyResponse", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.OgloszeniaWgCenyResponse")
    public List<OgloszenieSamochodowe> ogloszeniaWgCeny(
        @WebParam(name = "min", targetNamespace = "")
        BigDecimal min,
        @WebParam(name = "max", targetNamespace = "")
        BigDecimal max)
        throws BladBazyDanych_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ogloszenia.wygenerowane.OgloszenieSamochodowe>
     * @throws BladBazyDanych_Exception
     */
    @WebMethod
    @WebResult(name = "ogloszenie", targetNamespace = "")
    @RequestWrapper(localName = "wszystkieOgloszenia", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.WszystkieOgloszenia")
    @ResponseWrapper(localName = "wszystkieOgloszeniaResponse", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.WszystkieOgloszeniaResponse")
    public List<OgloszenieSamochodowe> wszystkieOgloszenia()
        throws BladBazyDanych_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns ogloszenia.wygenerowane.OgloszenieSamochodowe
     * @throws NieznanyRekord_Exception
     * @throws BladBazyDanych_Exception
     */
    @WebMethod
    @WebResult(name = "ogloszenie", targetNamespace = "")
    @RequestWrapper(localName = "jednoOgloszenie", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.JednoOgloszenie")
    @ResponseWrapper(localName = "jednoOgloszenieResponse", targetNamespace = "http://soap.ogloszenia/", className = "ogloszenia.wygenerowane.JednoOgloszenieResponse")
    public OgloszenieSamochodowe jednoOgloszenie(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws BladBazyDanych_Exception, NieznanyRekord_Exception
    ;

}
