//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.29 at 02:28:09 PM CET 
//


package rozwiazane_zadania.zad12.sklep;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Obiekt tej klasy reprezentuje pojedynczy towar w sklepie.
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTowar", propOrder = {
    "nazwa",
    "opis",
    "cenaNetto",
    "podatekVat",
    "cenaPromocyjna"
})
public class Towar {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nazwa;
    protected TTekst opis;
    @XmlElement(name = "cena", required = true)
    protected BigDecimal cenaNetto;
    @XmlElement(name = "vat", required = true)
    protected BigDecimal podatekVat;
    @XmlElement(name = "cena-promocyjna")
    protected List<Towar.CenaPromocyjna> cenaPromocyjna;
    @XmlAttribute(name = "id-towaru", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String idTowaru;
    @XmlAttribute(name = "id-kategorii")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String idKategorii;

    /**
     * Gets the value of the nazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwa() {
        return nazwa;
    }

    /**
     * Sets the value of the nazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwa(String value) {
        this.nazwa = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link TTekst }
     *     
     */
    public TTekst getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTekst }
     *     
     */
    public void setOpis(TTekst value) {
        this.opis = value;
    }

    /**
     * Gets the value of the cenaNetto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCenaNetto() {
        return cenaNetto;
    }

    /**
     * Sets the value of the cenaNetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCenaNetto(BigDecimal value) {
        this.cenaNetto = value;
    }

    /**
     * Gets the value of the podatekVat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatekVat() {
        return podatekVat;
    }

    /**
     * Sets the value of the podatekVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatekVat(BigDecimal value) {
        this.podatekVat = value;
    }

    /**
     * Gets the value of the cenaPromocyjna property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cenaPromocyjna property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCenaPromocyjna().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Towar.CenaPromocyjna }
     * 
     * 
     */
    public List<Towar.CenaPromocyjna> getCenaPromocyjna() {
        if (cenaPromocyjna == null) {
            cenaPromocyjna = new ArrayList<Towar.CenaPromocyjna>();
        }
        return this.cenaPromocyjna;
    }

    /**
     * Gets the value of the idTowaru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTowaru() {
        return idTowaru;
    }

    /**
     * Sets the value of the idTowaru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTowaru(String value) {
        this.idTowaru = value;
    }

    /**
     * Gets the value of the idKategorii property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdKategorii() {
        return idKategorii;
    }

    /**
     * Sets the value of the idKategorii property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdKategorii(String value) {
        this.idKategorii = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:sklep>TKwota">
     *       &lt;attGroup ref="{urn:sklep}APrzedział"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CenaPromocyjna {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "od", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar od;
        @XmlAttribute(name = "do", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar _do;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the od property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOd() {
            return od;
        }

        /**
         * Sets the value of the od property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOd(XMLGregorianCalendar value) {
            this.od = value;
        }

        /**
         * Gets the value of the do property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDo() {
            return _do;
        }

        /**
         * Sets the value of the do property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDo(XMLGregorianCalendar value) {
            this._do = value;
        }

    }

}
