package kalkulator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-23T09:16:56.018+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://www.example.org/KalkulatorRPC/", name = "KalkulatorRPC")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface KalkulatorRPC {

    @WebMethod(action = "http://www.example.org/KalkulatorRPC/sub")
    @WebResult(name = "result", targetNamespace = "http://www.example.org/KalkulatorRPC/", partName = "result")
    public int sub(

        @WebParam(partName = "arg1", name = "arg1")
        int arg1,
        @WebParam(partName = "arg2", name = "arg2")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/KalkulatorRPC/add")
    @WebResult(name = "result", targetNamespace = "http://www.example.org/KalkulatorRPC/", partName = "result")
    public int add(

        @WebParam(partName = "arg1", name = "arg1")
        int arg1,
        @WebParam(partName = "arg2", name = "arg2")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/KalkulatorRPC/mul")
    @WebResult(name = "result", targetNamespace = "http://www.example.org/KalkulatorRPC/", partName = "result")
    public int mul(

        @WebParam(partName = "arg1", name = "arg1")
        int arg1,
        @WebParam(partName = "arg2", name = "arg2")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/KalkulatorRPC/inc")
    @WebResult(name = "incResponse", targetNamespace = "http://www.example.org/KalkulatorRPC/", partName = "incResponse")
    public int inc(

        @WebParam(partName = "incRequest", name = "incRequest")
        int incRequest
    );
}
