//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 02:03:42 PM CET 
//


package wygenerowane2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the wygenerowane2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ogloszenie_QNAME = new QName("", "ogloszenie");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wygenerowane2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OgloszenieMotoryzacyjne }
     * 
     */
    public OgloszenieMotoryzacyjne createOgloszenieMotoryzacyjne() {
        return new OgloszenieMotoryzacyjne();
    }

    /**
     * Create an instance of {@link Ogloszenie }
     * 
     */
    public Ogloszenie createOgloszenie() {
        return new Ogloszenie();
    }

    /**
     * Create an instance of {@link Adres }
     * 
     */
    public Adres createAdres() {
        return new Adres();
    }

    /**
     * Create an instance of {@link Silnik }
     * 
     */
    public Silnik createSilnik() {
        return new Silnik();
    }

    /**
     * Create an instance of {@link Sprzedawca }
     * 
     */
    public Sprzedawca createSprzedawca() {
        return new Sprzedawca();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OgloszenieMotoryzacyjne }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ogloszenie")
    public JAXBElement<OgloszenieMotoryzacyjne> createOgloszenie(OgloszenieMotoryzacyjne value) {
        return new JAXBElement<OgloszenieMotoryzacyjne>(_Ogloszenie_QNAME, OgloszenieMotoryzacyjne.class, null, value);
    }

}
