//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.29 at 11:39:09 AM CET 
//


package rozwiazane_zadania.zad09.klasy_jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zad09.klasy_jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TTekstTerm_QNAME = new QName("", "term");
    private final static QName _TTekstLink_QNAME = new QName("", "link");
    private final static QName _TTekstRem_QNAME = new QName("", "rem");
    private final static QName _TTekstEm_QNAME = new QName("", "em");
    private final static QName _TTekstBr_QNAME = new QName("", "br");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zad09.klasy_jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link TTowar }
     * 
     */
    public TTowar createTTowar() {
        return new TTowar();
    }

    /**
     * Create an instance of {@link Cenniki }
     * 
     */
    public Cenniki createCenniki() {
        return new Cenniki();
    }

    /**
     * Create an instance of {@link Cennik }
     * 
     */
    public Cennik createCennik() {
        return new Cennik();
    }

    /**
     * Create an instance of {@link Sklep }
     * 
     */
    public Sklep createSklep() {
        return new Sklep();
    }

    /**
     * Create an instance of {@link TKategoria }
     * 
     */
    public TKategoria createTKategoria() {
        return new TKategoria();
    }

    /**
     * Create an instance of {@link TTekst.Br }
     * 
     */
    public TTekst.Br createTTekstBr() {
        return new TTekst.Br();
    }

    /**
     * Create an instance of {@link TTekst.Link }
     * 
     */
    public TTekst.Link createTTekstLink() {
        return new TTekst.Link();
    }

    /**
     * Create an instance of {@link TTowar.CenaPromocyjna }
     * 
     */
    public TTowar.CenaPromocyjna createTTowarCenaPromocyjna() {
        return new TTowar.CenaPromocyjna();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "term", scope = TTekst.class)
    public JAXBElement<TTekst> createTTekstTerm(TTekst value) {
        return new JAXBElement<TTekst>(_TTekstTerm_QNAME, TTekst.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link", scope = TTekst.class)
    public JAXBElement<TTekst.Link> createTTekstLink(TTekst.Link value) {
        return new JAXBElement<TTekst.Link>(_TTekstLink_QNAME, TTekst.Link.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rem", scope = TTekst.class)
    public JAXBElement<TTekst> createTTekstRem(TTekst value) {
        return new JAXBElement<TTekst>(_TTekstRem_QNAME, TTekst.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "em", scope = TTekst.class)
    public JAXBElement<TTekst> createTTekstEm(TTekst value) {
        return new JAXBElement<TTekst>(_TTekstEm_QNAME, TTekst.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.Br }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "br", scope = TTekst.class)
    public JAXBElement<TTekst.Br> createTTekstBr(TTekst.Br value) {
        return new JAXBElement<TTekst.Br>(_TTekstBr_QNAME, TTekst.Br.class, TTekst.class, value);
    }

}
