package kalkulator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-23T11:36:05.026+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://www.example.org/KalkulatorBare/", name = "KalkulatorBare")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface KalkulatorBare {

    @WebMethod(action = "http://www.example.org/KalkulatorBare/sub")
    @WebResult(name = "subOutput", targetNamespace = "http://www.example.org/KalkulatorBare/", partName = "parameters")
    public SubOutput sub(

        @WebParam(partName = "parameters", name = "subInput", targetNamespace = "http://www.example.org/KalkulatorBare/")
        SubInput parameters
    );

    @WebMethod(action = "http://www.example.org/KalkulatorBare/add")
    @WebResult(name = "addOutput", targetNamespace = "http://www.example.org/KalkulatorBare/", partName = "parameters")
    public AddOutput add(

        @WebParam(partName = "parameters", name = "addInput", targetNamespace = "http://www.example.org/KalkulatorBare/")
        AddInput parameters
    );

    @WebMethod(action = "http://www.example.org/KalkulatorBare/div")
    @WebResult(name = "divOutput", targetNamespace = "http://www.example.org/KalkulatorBare/", partName = "parameters")
    public DivOutput div(

        @WebParam(partName = "parameters", name = "divInput", targetNamespace = "http://www.example.org/KalkulatorBare/")
        DivInput parameters
    );

    @WebMethod(action = "http://www.example.org/KalkulatorBare/inc")
    @WebResult(name = "incOutput", targetNamespace = "http://www.example.org/KalkulatorBare/", partName = "parameters")
    public IncOutput inc(

        @WebParam(partName = "parameters", name = "incInput", targetNamespace = "http://www.example.org/KalkulatorBare/")
        IncInput parameters
    );
}
