package kalkulator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-23T11:36:05.060+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "KalkulatorBare",
                  wsdlLocation = "file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC05-KalkulatorDocumentBare/WebContent/WEB-INF/wsdl/KalkulatorBare.wsdl",
                  targetNamespace = "http://www.example.org/KalkulatorBare/")
public class KalkulatorBare_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/KalkulatorBare/", "KalkulatorBare");
    public final static QName KalkulatorBareSOAP = new QName("http://www.example.org/KalkulatorBare/", "KalkulatorBareSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC05-KalkulatorDocumentBare/WebContent/WEB-INF/wsdl/KalkulatorBare.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KalkulatorBare_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC05-KalkulatorDocumentBare/WebContent/WEB-INF/wsdl/KalkulatorBare.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KalkulatorBare_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KalkulatorBare_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KalkulatorBare_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public KalkulatorBare_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KalkulatorBare_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KalkulatorBare_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns KalkulatorBare
     */
    @WebEndpoint(name = "KalkulatorBareSOAP")
    public KalkulatorBare getKalkulatorBareSOAP() {
        return super.getPort(KalkulatorBareSOAP, KalkulatorBare.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KalkulatorBare
     */
    @WebEndpoint(name = "KalkulatorBareSOAP")
    public KalkulatorBare getKalkulatorBareSOAP(WebServiceFeature... features) {
        return super.getPort(KalkulatorBareSOAP, KalkulatorBare.class, features);
    }

}
